on:
  push:
    tags:
        - 'v*'

jobs:
    build:
        name: Create Release
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Get the version
          id: get_version
          run: echo ::set-output name=VERSION::$(cat version)            
        - name: Create Release
          uses: softprops/action-gh-release@v1
          if: startsWith(github.ref, 'refs/tags/')
          with:
            name: Release of ${{ steps.get_version.outputs.VERSION }}
            files: .pio/build/esp32dev/firmware.bin
            draft: true
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_ACTION_TOKEN }}
